services:
  mariadb:
    image: docker.io/bitnami/mariadb:11.4
    volumes:
      - 'mariadb_data:/bitnami/mariadb:rw'
    environment:
      - MARIADB_ROOT_PASSWORD=${ADMIN_PASSWORD}
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - MARIADB_PASSWORD=${ADMIN_PASSWORD}
  mailpit:
    image: axllent/mailpit
    ports:
      - "8025:8025" # Web UI port for viewing intercepted emails
  wordpress:
    image: docker.io/bitnami/wordpress:6
    ports:
      - '8080:8080'
      - '8443:8443'
    volumes:
      - 'wordpress_data:/bitnami/wordpress:rw'
      # Mount plugin source for live development
      - ./storelocator-list:/bitnami/wordpress/wp-content/plugins/storelocator-list:rw
    depends_on:
      - mariadb
    environment:
      - WORDPRESS_USERNAME=admin
      - WORDPRESS_PASSWORD=${ADMIN_PASSWORD}
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - WORDPRESS_DATABASE_PASSWORD=${ADMIN_PASSWORD}
      - PHP_POST_MAX_SIZE=80M
      - PHP_UPLOAD_MAX_FILESIZE=80M

volumes:
  mariadb_data:
    external: true
    # driver: local
  wordpress_data:
    external: true
    # driver: local 
 